name: Tests
  
on:  
  push:
    branches: [ main ]
  pull_request:  
    branches: [ main ]  
  
jobs:  
  test:  
    runs-on: ubuntu-latest  
    container:  
      image: python:3.12-slim-bullseye  
  
    steps:  
      - name: Checkout code  
        uses: actions/checkout@v2  
  
      - name: Install dependencies  
        run: |  
          apt-get update && apt-get install -y libc-dev libffi-dev libjpeg-dev ffmpeg gcc
          python -m pip install --upgrade pip  
          pip install -r requirements/base.txt
          pip install -r requirements/dev.txt
  
      - name: Run pytest  
        run: |  
          pytest  
  
  lint:  
    runs-on: ubuntu-latest 
    container:  
      image: python:3.12-slim-bullseye  
  
    steps:  
      - name: Checkout code  
        uses: actions/checkout@v2  
  
      - name: Install dependencies  
        run: |  
          apt-get update && apt-get install -y libc-dev libffi-dev libjpeg-dev ffmpeg gcc
          python -m pip install --upgrade pip  
          pip install -r requirements/base.txt
          pip install -r requirements/dev.txt
  
      - name: Run pyright  
        run: pyright  
